
2022-01-03 18:26:55,069 :: INFO :: Training stdgi ||  interpolate False || attention decoder False || epochs 0 || lr 0.005
  0%|                                                                                                                                                                                      | 0/31 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_attention_stdgi.py", line 229, in <module>
    list_prd,list_grt = test_atten_decoder_fn(stdgi,decoder,test_dataloader,device, args.interpolate,scaler)
  File "/home/aiotlabws/Workspace/Project/hungvv/stdgi/src/modules/train/test.py", line 41, in test_atten_decoder_fn
    y_prd = decoder(x[-1].unsqueeze(0), h, l)  # 3x1x1
  File "/home/aiotlabws/Workspace/Env/anaconda3/envs/longnd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aiotlabws/Workspace/Project/hungvv/stdgi/src/models/decoder.py", line 47, in forward
    x_ = x_.permute(0,2,1)
RuntimeError: number of dims don't match in permute